# fly.toml app configuration file generated for tipseeart on 2023-04-29T09:09:22-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "tipseeart"
primary_region = "atl"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
