"""empty message

Revision ID: 1e0f1fbbd086
Revises: e6eb7b77909c
Create Date: 2023-02-07 14:13:02.483325

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1e0f1fbbd086'
down_revision = 'e6eb7b77909c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
