"""empty message

Revision ID: 2e730795ebfe
Revises: b07f757f763e
Create Date: 2023-04-30 13:01:37.247385

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "2e730795ebfe"
down_revision = "b07f757f763e"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    social_media = op.create_table(
        "social_media",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("url", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_social_media_id"), "social_media", ["id"], unique=False)

    op.bulk_insert(
        social_media,
        [
            {"id": 1, "name": "other", "url": "{}"},
            {"id": 2, "name": "twitter", "url": "https://twitter.com/{}"},
            {"id": 3, "name": "facebook", "url": "https://facebook.com/{}"},
            {"id": 4, "name": "youtube", "url": "https://youtube.com/@{}"},
            {"id": 5, "name": "instagram", "url": "https://instagram.com/{}"},
            {"id": 6, "name": "linkedin", "url": "https://linkedin.com/in/{}"},
            {"id": 7, "name": "bandcamp", "url": "https://{}.bandcamp.com"},
            {"id": 8, "name": "soundcloud", "url": "https://soundcloud.com/{}"},
            {"id": 10, "name": "portfolio", "url": "{}"},
            {"id": 11, "name": "tiktok", "url": "https://www.tiktok.com/@{}"},
            {"id": 12, "name": "etsy", "url": "https://www.etsy.com/shop/{}"},
            {"id": 13, "name": "twitch", "url": "https://www.twitch.tv/{}"},
            {"id": 14, "name": "reddit", "url": "https://www.reddit.com/user/{}"},
            {"id": 15, "name": "pinterest", "url": "https://www.pinterest.com/{}/"},
        ],
    )
    op.create_table(
        "social_links",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("artist_id", sa.Integer(), nullable=True),
        sa.Column("social_media_id", sa.Integer(), nullable=True),
        sa.Column("username", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["artist_id"],
            ["artists.id"],
        ),
        sa.ForeignKeyConstraint(
            ["social_media_id"],
            ["social_media.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_social_links_id"), "social_links", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_social_links_id"), table_name="social_links")
    op.drop_table("social_links")
    op.drop_index(op.f("ix_social_media_id"), table_name="social_media")
    op.drop_table("social_media")
    # ### end Alembic commands ###
