"""empty message

Revision ID: 36a781578b22
Revises: 4d2ce0a77929
Create Date: 2023-04-29 14:42:16.315275

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '36a781578b22'
down_revision = '4d2ce0a77929'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
