"""empty message

Revision ID: 5bd2e30a10d8
Revises: 1e0f1fbbd086
Create Date: 2023-04-18 16:58:20.754326

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "5bd2e30a10d8"
down_revision = "1e0f1fbbd086"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "tags", sa.Column("severity", sa.Integer(), nullable=False, server_default="1")
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("tags", "severity")
    # ### end Alembic commands ###
