"""empty message

Revision ID: 61a595c2f015
Revises: 2e730795ebfe
Create Date: 2023-04-30 13:53:31.215242

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '61a595c2f015'
down_revision = '2e730795ebfe'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('media', sa.Column('url', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('media', 'url')
    # ### end Alembic commands ###
