"""empty message

Revision ID: e6eb7b77909c
Revises: ffd2b1d75283
Create Date: 2023-02-05 01:14:15.245505

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e6eb7b77909c'
down_revision = 'ffd2b1d75283'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tags', sa.Column('name', sa.String(), nullable=False))
    op.drop_column('tags', 'tag_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tags', sa.Column('tag_name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('tags', 'name')
    # ### end Alembic commands ###
