"""empty message

Revision ID: ff2e80186c25
Revises: 8805631d46fe
Create Date: 2023-04-29 14:43:30.881938

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff2e80186c25'
down_revision = '8805631d46fe'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payment_urls',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('artist_id', sa.Integer(), nullable=True),
    sa.Column('payment_provider_id', sa.Integer(), nullable=True),
    sa.Column('username', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['artist_id'], ['artists.id'], ),
    sa.ForeignKeyConstraint(['payment_provider_id'], ['payment_providers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payment_urls_id'), 'payment_urls', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_payment_urls_id'), table_name='payment_urls')
    op.drop_table('payment_urls')
    # ### end Alembic commands ###
